controller_frequency: 15.0
TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.10
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 1.0
  min_vel_theta: -1.0

  min_in_place_rotational_vel: 0.4
  escape_vel: -0.1
  acc_lim_theta: 0.5
  acc_lim_x: 0.40
  acc_lim_y: 0.0



  holonomic_robot: false
  yaw_goal_tolerance: 0.2 # about 6 degrees
  xy_goal_tolerance: 0.2  # 5 cm
  latch_xy_goal_tolerance: false
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  meter_scoring: true

  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  occdist_scale: 0.05
  oscillation_reset_dist: 0.05
  publish_cost_grid_pc: false
  prune_plan: true

  sim_time: 1.0
  sim_granularity: 0.05
  angular_sim_granularity: 0.1
  vx_samples: 6
  vy_samples: 0  # zero for a differential drive robot
  vtheta_samples: 20
  dwa: false
  simple_attractor: false

