obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.17, -0.20], [-0.20, -0.10], [-0.225, 0.0], [-0.20, 0.10], [-0.17, 0.20], [0.10, 0.20], [0.17, 0.10], [0.225, 0.0], [0.17, -0.10], [0.10, -0.20]]
footprint_padding: 0.01
inflation_radius: 0.2
max_obstacle_height: 1.0 # 最大障碍物高度
min_obstacle_height: 0.0 # 最小障碍物高度


observation_sources: point_cloud_sensor scan
point_cloud_sensor: { sensor_frame: sonar, data_type: PointCloud2, topic: /rosaria/sonar_pointcloud2, marking: true, clearing: true,}

scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
